# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "65f0f4afb15aff3259b044d4ebd4c271"
name = "GoatjumpPay"
application_url = "https://gjcustompay-production.up.railway.app"
embedded = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_payment_customizations, read_payment_customizations"

[auth]
redirect_urls = [
  "https://gjcustompay-production.up.railway.app/auth/callback",
  "https://gjcustompay-production.up.railway.app/auth/shopify/callback"
]
