api_version = "2024-07"

[[extensions]]
name = "payment-customization"
handle = "payment-customization"

uid = "4f8a281d-8599-ed4f-dd32-1297c2872b96939fbf00"

type = "function"
description = "Hides payment methods based on collections"

  [[extensions.targeting]]
  target = "purchase.payment-customization.run"
  input_query = "src/run.graphql"
  export = "run"

[extensions.build]
command = "npm run build"
path = "dist/function.wasm"
